--------------------------------------------------------
-- Archivo creado  - viernes-mayo-19-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANALISIS_CLINICO_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."ANALISIS_CLINICO_IHB" 
   (	"ID_ANALISISCLINICO" NUMBER(*,0), 
	"ID_CONSULTA" NUMBER(*,0), 
	"ID_TIPOANALISIS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASISTENTE_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."ASISTENTE_IHB" 
   (	"ID_ASISTENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"A_PATERNO" VARCHAR2(50 BYTE), 
	"A_MATERNO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."CITA_IHB" 
   (	"ID_CITA" NUMBER(*,0), 
	"ID_PACIENTE" NUMBER(*,0), 
	"ID_ASISTENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSULTA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."CONSULTA_IHB" 
   (	"ID_CONSULTA" NUMBER(*,0), 
	"ID_CITA" NUMBER(*,0), 
	"ID_MEDICO" NUMBER(*,0), 
	"NUM_CONSULTORIO" NUMBER(*,0), 
	"ID_TIPOCONSULTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSULTORIO_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."CONSULTORIO_IHB" 
   (	"NUM_CONSULTORIO" NUMBER(*,0), 
	"UBICACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUARTO_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."CUARTO_IHB" 
   (	"ID_CUARTO" NUMBER(*,0), 
	"UBICACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFERMERA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."ENFERMERA_IHB" 
   (	"ID_ENFERMERA" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APATERNO" VARCHAR2(50 BYTE), 
	"AMATERNO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXPEDIENTE_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."EXPEDIENTE_IHB" 
   (	"ID_EXPEDIENTE" NUMBER(10,0), 
	"CONSULTA_EXPEDIENTE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GENERA_EXPEDIENTE_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."GENERA_EXPEDIENTE_IHB" 
   (	"ID_GENERA_EXPEDIENTE" NUMBER(10,0), 
	"CONSULTA_GENERA_EXPEDIENTE" NUMBER(10,0), 
	"EXPEDIENTE_GENERA_EXPEDIENTE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOSPITALIZACION_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."HOSPITALIZACION_IHB" 
   (	"ID_HOSPITALIZACION" NUMBER(*,0), 
	"ID_CONSULTA" NUMBER(*,0), 
	"ID_CUARTO" NUMBER(*,0), 
	"ID_ENFERMERA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."MEDICAMENTO_IHB" 
   (	"ID_MEDICAMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICO_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."MEDICO_IHB" 
   (	"ID_MEDICO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"A_PATERNO" VARCHAR2(50 BYTE), 
	"A_MATERNO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE_CITA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."PACIENTE_CITA_IHB" 
   (	"ID_PACIENTE_CITA" NUMBER(10,0), 
	"PACIENTE_PACIENTE_CITA" NUMBER(10,0), 
	"ASISTENTE_PACIENTE_CITA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."PACIENTE_IHB" 
   (	"ID_PACIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"A_PATERNO" VARCHAR2(50 BYTE), 
	"A_MATERNO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAGO_CONSULTA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."PAGO_CONSULTA_IHB" 
   (	"ID_PAGO_CONSULTA" NUMBER(10,0), 
	"FECHA_PAGO" DATE, 
	"MONTO_PAGADO" NUMBER(10,2), 
	"CONSULTA_PAGO_CONSULTA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."RECETA_IHB" 
   (	"ID_RECETA" NUMBER(*,0), 
	"ID_CONSULTA" NUMBER(*,0), 
	"ID_MEDICAMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_ANALISIS_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."TIPO_ANALISIS_IHB" 
   (	"ID_TIPOANALISIS" NUMBER(*,0), 
	"NOMBRE_TIPOANALISIS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CONSULTA_IHB
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."TIPO_CONSULTA_IHB" 
   (	"ID_TIPOCONSULTA" NUMBER(*,0), 
	"NOMBRE_TIPOCONSULTA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOSPITAL.ANALISIS_CLINICO_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.ASISTENTE_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.CITA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.CONSULTA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.CONSULTORIO_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.CUARTO_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.ENFERMERA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.EXPEDIENTE_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.GENERA_EXPEDIENTE_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.HOSPITALIZACION_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.MEDICAMENTO_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.MEDICO_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.PACIENTE_CITA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.PACIENTE_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.PAGO_CONSULTA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.RECETA_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.TIPO_ANALISIS_IHB
SET DEFINE OFF;
REM INSERTING into HOSPITAL.TIPO_CONSULTA_IHB
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007094
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007094" ON "HOSPITAL"."ENFERMERA_IHB" ("ID_ENFERMERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007095
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007095" ON "HOSPITAL"."PACIENTE_IHB" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007096
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007096" ON "HOSPITAL"."ASISTENTE_IHB" ("ID_ASISTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007097
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007097" ON "HOSPITAL"."MEDICO_IHB" ("ID_MEDICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007098
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007098" ON "HOSPITAL"."CUARTO_IHB" ("ID_CUARTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007099
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007099" ON "HOSPITAL"."MEDICAMENTO_IHB" ("ID_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007100
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007100" ON "HOSPITAL"."TIPO_ANALISIS_IHB" ("ID_TIPOANALISIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007101
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007101" ON "HOSPITAL"."TIPO_CONSULTA_IHB" ("ID_TIPOCONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007102
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007102" ON "HOSPITAL"."CONSULTORIO_IHB" ("NUM_CONSULTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007103
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007103" ON "HOSPITAL"."CITA_IHB" ("ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007106
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007106" ON "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007111
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007111" ON "HOSPITAL"."HOSPITALIZACION_IHB" ("ID_HOSPITALIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007115
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007115" ON "HOSPITAL"."ANALISIS_CLINICO_IHB" ("ID_ANALISISCLINICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007118
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007118" ON "HOSPITAL"."RECETA_IHB" ("ID_RECETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007123
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007123" ON "HOSPITAL"."PAGO_CONSULTA_IHB" ("ID_PAGO_CONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007125
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007125" ON "HOSPITAL"."PACIENTE_CITA_IHB" ("ID_PACIENTE_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007128
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007128" ON "HOSPITAL"."EXPEDIENTE_IHB" ("ID_EXPEDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007130
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007130" ON "HOSPITAL"."GENERA_EXPEDIENTE_IHB" ("ID_GENERA_EXPEDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007115
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007115" ON "HOSPITAL"."ANALISIS_CLINICO_IHB" ("ID_ANALISISCLINICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007096
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007096" ON "HOSPITAL"."ASISTENTE_IHB" ("ID_ASISTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007103
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007103" ON "HOSPITAL"."CITA_IHB" ("ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007106
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007106" ON "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007102
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007102" ON "HOSPITAL"."CONSULTORIO_IHB" ("NUM_CONSULTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007098
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007098" ON "HOSPITAL"."CUARTO_IHB" ("ID_CUARTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007094
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007094" ON "HOSPITAL"."ENFERMERA_IHB" ("ID_ENFERMERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007128
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007128" ON "HOSPITAL"."EXPEDIENTE_IHB" ("ID_EXPEDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007130
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007130" ON "HOSPITAL"."GENERA_EXPEDIENTE_IHB" ("ID_GENERA_EXPEDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007111
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007111" ON "HOSPITAL"."HOSPITALIZACION_IHB" ("ID_HOSPITALIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007099
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007099" ON "HOSPITAL"."MEDICAMENTO_IHB" ("ID_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007097
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007097" ON "HOSPITAL"."MEDICO_IHB" ("ID_MEDICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007125
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007125" ON "HOSPITAL"."PACIENTE_CITA_IHB" ("ID_PACIENTE_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007095
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007095" ON "HOSPITAL"."PACIENTE_IHB" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007123
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007123" ON "HOSPITAL"."PAGO_CONSULTA_IHB" ("ID_PAGO_CONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007118
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007118" ON "HOSPITAL"."RECETA_IHB" ("ID_RECETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007100
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007100" ON "HOSPITAL"."TIPO_ANALISIS_IHB" ("ID_TIPOANALISIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007101
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."SYS_C007101" ON "HOSPITAL"."TIPO_CONSULTA_IHB" ("ID_TIPOCONSULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANALISIS_CLINICO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."ANALISIS_CLINICO_IHB" ADD PRIMARY KEY ("ID_ANALISISCLINICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASISTENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."ASISTENTE_IHB" ADD PRIMARY KEY ("ID_ASISTENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CITA_IHB" ADD PRIMARY KEY ("ID_CITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSULTA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CONSULTA_IHB" ADD PRIMARY KEY ("ID_CONSULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSULTORIO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CONSULTORIO_IHB" ADD PRIMARY KEY ("NUM_CONSULTORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUARTO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CUARTO_IHB" ADD PRIMARY KEY ("ID_CUARTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENFERMERA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."ENFERMERA_IHB" ADD PRIMARY KEY ("ID_ENFERMERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPEDIENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."EXPEDIENTE_IHB" ADD PRIMARY KEY ("ID_EXPEDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GENERA_EXPEDIENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."GENERA_EXPEDIENTE_IHB" ADD PRIMARY KEY ("ID_GENERA_EXPEDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOSPITALIZACION_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."HOSPITALIZACION_IHB" ADD PRIMARY KEY ("ID_HOSPITALIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."MEDICAMENTO_IHB" ADD PRIMARY KEY ("ID_MEDICAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."MEDICO_IHB" ADD PRIMARY KEY ("ID_MEDICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACIENTE_CITA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."PACIENTE_CITA_IHB" ADD PRIMARY KEY ("ID_PACIENTE_CITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACIENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."PACIENTE_IHB" ADD PRIMARY KEY ("ID_PACIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGO_CONSULTA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."PAGO_CONSULTA_IHB" ADD PRIMARY KEY ("ID_PAGO_CONSULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSPITAL"."PAGO_CONSULTA_IHB" MODIFY ("MONTO_PAGADO" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."PAGO_CONSULTA_IHB" MODIFY ("FECHA_PAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."RECETA_IHB" ADD PRIMARY KEY ("ID_RECETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_ANALISIS_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."TIPO_ANALISIS_IHB" ADD PRIMARY KEY ("ID_TIPOANALISIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_CONSULTA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."TIPO_CONSULTA_IHB" ADD PRIMARY KEY ("ID_TIPOCONSULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALISIS_CLINICO_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."ANALISIS_CLINICO_IHB" ADD FOREIGN KEY ("ID_CONSULTA")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
  ALTER TABLE "HOSPITAL"."ANALISIS_CLINICO_IHB" ADD FOREIGN KEY ("ID_TIPOANALISIS")
	  REFERENCES "HOSPITAL"."TIPO_ANALISIS_IHB" ("ID_TIPOANALISIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CITA_IHB" ADD FOREIGN KEY ("ID_PACIENTE")
	  REFERENCES "HOSPITAL"."PACIENTE_IHB" ("ID_PACIENTE") ENABLE;
  ALTER TABLE "HOSPITAL"."CITA_IHB" ADD FOREIGN KEY ("ID_ASISTENTE")
	  REFERENCES "HOSPITAL"."ASISTENTE_IHB" ("ID_ASISTENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSULTA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."CONSULTA_IHB" ADD FOREIGN KEY ("ID_CITA")
	  REFERENCES "HOSPITAL"."CITA_IHB" ("ID_CITA") ENABLE;
  ALTER TABLE "HOSPITAL"."CONSULTA_IHB" ADD FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "HOSPITAL"."MEDICO_IHB" ("ID_MEDICO") ENABLE;
  ALTER TABLE "HOSPITAL"."CONSULTA_IHB" ADD FOREIGN KEY ("NUM_CONSULTORIO")
	  REFERENCES "HOSPITAL"."CONSULTORIO_IHB" ("NUM_CONSULTORIO") ENABLE;
  ALTER TABLE "HOSPITAL"."CONSULTA_IHB" ADD FOREIGN KEY ("ID_TIPOCONSULTA")
	  REFERENCES "HOSPITAL"."TIPO_CONSULTA_IHB" ("ID_TIPOCONSULTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPEDIENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."EXPEDIENTE_IHB" ADD FOREIGN KEY ("CONSULTA_EXPEDIENTE")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GENERA_EXPEDIENTE_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."GENERA_EXPEDIENTE_IHB" ADD FOREIGN KEY ("CONSULTA_GENERA_EXPEDIENTE")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
  ALTER TABLE "HOSPITAL"."GENERA_EXPEDIENTE_IHB" ADD FOREIGN KEY ("EXPEDIENTE_GENERA_EXPEDIENTE")
	  REFERENCES "HOSPITAL"."EXPEDIENTE_IHB" ("ID_EXPEDIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOSPITALIZACION_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."HOSPITALIZACION_IHB" ADD FOREIGN KEY ("ID_CONSULTA")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
  ALTER TABLE "HOSPITAL"."HOSPITALIZACION_IHB" ADD FOREIGN KEY ("ID_CUARTO")
	  REFERENCES "HOSPITAL"."CUARTO_IHB" ("ID_CUARTO") ENABLE;
  ALTER TABLE "HOSPITAL"."HOSPITALIZACION_IHB" ADD FOREIGN KEY ("ID_ENFERMERA")
	  REFERENCES "HOSPITAL"."ENFERMERA_IHB" ("ID_ENFERMERA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PACIENTE_CITA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."PACIENTE_CITA_IHB" ADD FOREIGN KEY ("PACIENTE_PACIENTE_CITA")
	  REFERENCES "HOSPITAL"."PACIENTE_IHB" ("ID_PACIENTE") ENABLE;
  ALTER TABLE "HOSPITAL"."PACIENTE_CITA_IHB" ADD FOREIGN KEY ("ASISTENTE_PACIENTE_CITA")
	  REFERENCES "HOSPITAL"."ASISTENTE_IHB" ("ID_ASISTENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGO_CONSULTA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."PAGO_CONSULTA_IHB" ADD FOREIGN KEY ("CONSULTA_PAGO_CONSULTA")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECETA_IHB
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."RECETA_IHB" ADD FOREIGN KEY ("ID_CONSULTA")
	  REFERENCES "HOSPITAL"."CONSULTA_IHB" ("ID_CONSULTA") ENABLE;
  ALTER TABLE "HOSPITAL"."RECETA_IHB" ADD FOREIGN KEY ("ID_MEDICAMENTO")
	  REFERENCES "HOSPITAL"."MEDICAMENTO_IHB" ("ID_MEDICAMENTO") ENABLE;
